create table if not exists call_scan_results (
  scan_result_id text primary key,
  foundation_id uuid not null references foundations(id) on delete cascade,
  program_id uuid references programs(id) on delete cascade,
  foundation_name text,
  program_name text,
  scan_url text not null,
  scan_status text not null default 'pending' check (scan_status in ('found', 'no_match', 'error')),
  match_type text,
  discovered_title text,
  discovered_url text,
  excerpt text,
  contact_name text,
  contact_email text,
  contact_phone text,
  contact_source_url text,
  scanned_at timestamptz not null,
  review_status text not null default 'new' check (review_status in ('new', 'reviewed', 'ignored'))
);

create table if not exists notification_subscriptions (
  id uuid primary key default gen_random_uuid(),
  subscription_key text not null unique,
  email text not null unique,
  notify_deadline_soon boolean not null default true,
  notify_new_foundation boolean not null default true,
  notify_new_call boolean not null default true,
  notify_favorite_update boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists favorite_foundations (
  id uuid primary key default gen_random_uuid(),
  favorite_key text not null unique,
  subscription_id uuid not null references notification_subscriptions(id) on delete cascade,
  foundation_id uuid not null references foundations(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(subscription_id, foundation_id)
);

create table if not exists notification_events (
  event_id text primary key,
  event_type text not null check (event_type in ('deadline_soon', 'new_foundation', 'new_call', 'favorite_update')),
  foundation_id uuid references foundations(id) on delete cascade,
  program_id uuid references programs(id) on delete cascade,
  deadline_id uuid references deadlines(id) on delete cascade,
  scan_result_id text references call_scan_results(scan_result_id) on delete cascade,
  title text not null,
  body text,
  event_date date,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create table if not exists scrape_runs (
  run_id bigint generated by default as identity primary key,
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  targets_checked integer not null default 0,
  changed_pages integer not null default 0,
  changes_detected integer not null default 0,
  auto_approved integer not null default 0,
  manual_review integer not null default 0,
  error_message text
);

create table if not exists scrape_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  run_id bigint not null references scrape_runs(run_id),
  foundation_id uuid not null references foundations(id) on delete cascade,
  url text not null,
  fetched_at timestamptz not null,
  http_status integer,
  content_hash text,
  content_text text,
  changed_since_last boolean not null default false,
  error_message text
);

create table if not exists foundation_extracted_fields (
  foundation_id uuid not null references foundations(id) on delete cascade,
  field_name text not null,
  field_value text not null,
  source_url text not null,
  confidence numeric not null default 0 check (confidence between 0 and 1),
  updated_at timestamptz not null,
  primary key (foundation_id, field_name)
);

create table if not exists foundation_field_changes (
  change_id bigint generated by default as identity primary key,
  run_id bigint not null references scrape_runs(run_id),
  foundation_id uuid not null references foundations(id) on delete cascade,
  field_name text not null check (field_name in ('deadlines', 'funding_amounts', 'contact_info', 'purpose_criteria')),
  old_value text,
  new_value text not null,
  source_url text not null,
  confidence numeric not null default 0 check (confidence between 0 and 1),
  significance text not null default 'medium' check (significance in ('low', 'medium', 'high')),
  validation_status text not null default 'manual_review'
    check (validation_status in ('approved_auto', 'manual_review', 'approved_manual', 'rejected')),
  detected_at timestamptz not null,
  decided_at timestamptz,
  decision_note text
);

create table if not exists scrape_notifications (
  notification_id bigint generated by default as identity primary key,
  run_id bigint not null references scrape_runs(run_id),
  subject text not null,
  body text not null,
  created_at timestamptz not null,
  sent_at timestamptz,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed', 'disabled')),
  error_message text
);

create index if not exists call_scan_results_foundation_idx on call_scan_results(foundation_id, scanned_at desc);
create index if not exists call_scan_results_review_idx on call_scan_results(review_status, scan_status);
create index if not exists notification_events_date_idx on notification_events(event_date);
create index if not exists scrape_snapshots_foundation_idx on scrape_snapshots(foundation_id, fetched_at desc);
create index if not exists field_changes_status_idx on foundation_field_changes(validation_status, detected_at desc);
create index if not exists scrape_notifications_status_idx on scrape_notifications(status, created_at);
