import { randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { execSqliteFile, runSqlite, sqlString } from "./sqlite_utils.mjs";
const scrypt = promisify(scryptCallback);
function clean(value, max=200){const s=String(value??"").trim();return s?s.slice(0,max):null;}
export function validateAccountInput(body={}){const email=clean(body.email,254)?.toLowerCase();const displayName=clean(body.display_name,160);const password=String(body.password||"");if(!email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return {ok:false,statusCode:400,message:"Skriv en gyldig emailadresse"};if(!displayName)return {ok:false,statusCode:400,message:"Navn skal udfyldes"};if(password.length<10)return {ok:false,statusCode:400,message:"Adgangskoden skal være mindst 10 tegn"};return {ok:true,email,display_name:displayName,password};}
export async function hashPassword(password){const salt=randomBytes(16).toString("hex");const key=(await scrypt(password,salt,64)).toString("hex");return `scrypt$${salt}$${key}`;}
export async function verifyPassword(password,encoded){const [,salt,key]=String(encoded||"").split("$");if(!salt||!key)return false;const derived=await scrypt(password,salt,64);const expected=Buffer.from(key,"hex");return expected.length===derived.length&&timingSafeEqual(expected,derived);}
export function createAuthRepository({sqlitePath,cwd=process.cwd(),schemaPath}){const schema=schemaPath||`${cwd}/database/project_management_schema.sql`;let ready;const init=()=>{ready ||= execSqliteFile(sqlitePath, schema, { cwd });return ready;};const query=async sql=>{await init();return runSqlite(sqlitePath,`PRAGMA foreign_keys=ON;\n${sql}`,{cwd});};return {initialize:init,async countAccounts(){return Number((await query("SELECT COUNT(*) AS count FROM accounts;"))[0]?.count||0);},async createAccount(input){const id=randomUUID();const role=(await this.countAccounts())===0?"admin":"member";await query(`INSERT INTO accounts(account_id,email,display_name,password_hash,system_role) VALUES (${sqlString(id)},${sqlString(input.email)},${sqlString(input.display_name)},${sqlString(await hashPassword(input.password))},${sqlString(role)});`);return (await query(`SELECT account_id,email,display_name,system_role,is_active FROM accounts WHERE account_id=${sqlString(id)};`))[0];},async findByEmail(email){return (await query(`SELECT * FROM accounts WHERE email=${sqlString(String(email).trim().toLowerCase())} AND is_active=1;`))[0]||null;},async getPublic(accountId){return (await query(`SELECT account_id,email,display_name,system_role,is_active FROM accounts WHERE account_id=${sqlString(accountId)} AND is_active=1;`))[0]||null;}};}
